name: surf_practice_magic_ball
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.6 # Dart SDK version
  flutter: ^3.10.6 # Flutter SDK version

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.3.0
  injectable: ^2.1.2
  get_it: ^7.6.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_bloc: ^8.1.3
  shake: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  retrofit_generator: ^7.0.8
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  injectable_generator: ^2.1.6
  freezed: ^2.4.1
flutter:

  uses-material-design: true
  
  assets:
    - lib/core/assets/images/ball.png
    - lib/core/assets/images/star.png
    - lib/core/assets/images/small_star.png
    - lib/core/assets/images/small_ellipse.png
    - lib/core/assets/images/ellipse.png
    # - assets/background.png
